# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 14Gamez Studio
email: 14gamezstudio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: ""
url: "https://14gamez.com"
twitter_username: 
github_username:
facebook_username: 14gamez

# Build settings
markdown: kramdown
